version: 2.1

jobs:
  run-unit-tests:
    working_directory: ~/circleci-rrt-tasker-project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Create venv and install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests and generate reports
          command: |
            . venv/bin/activate
            pytest --junitxml test-results/pytests.xml --cov=. --cov-report html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: htmlcov
workflows:
  main:
    jobs:
      - run-unit-tests
