version: 2.1

# orbs:
#   python: circleci/python@0.2.1

jobs:
  run-unit-tests:
    working_directory: ~/circleci-rrt-tasker-project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Create venv, install dependencies, run tests and generate reports
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pytest --junitxml pytests.xml --cov=entities.TaskData --cov-report xml:coverage.xml -q tests/unittests/TestTaskDataMethods.py
      - store_test_results:
          path: pytests.xml
workflows:
  main:
    jobs:
      - run-unit-tests
